version: "3.9"

x-base: &default-config
  restart: unless-stopped
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000
  stop_grace_period: 1m
  logging:
    driver: json-file
    options:
      max-size: '100m'
      max-file: '1'
  mem_swappiness: 0

services:
  server:
    image: caddy:2
    << : *default-config
    ports:
      - 9090:80
    volumes:
      - ${PWD}/Caddyfile:/etc/caddy/Caddyfile
      #- /opt/data/docker:/data
      - /data/docker/caddy:/data
      - ${PWD}/config:/config

networks:
  default:
    external: true
    name: app
