apiVersion: v1
kind: Pod
metadata:
  name: caddy
spec:
  containers:
  - image: caddy
    name: caddy
    ports:
    - containerPort: 80
      hostPort: 8080
      protocol: TCP
    volumeMounts:
    - mountPath: /etc/caddy/Caddyfile
      name: caddyfile
    - mountPath: /data
      name: data

  volumes:
  - name: caddyfile
    hostPath:
      # 宿主上目录位置
      path: /root/workspace/caddy/Caddyfile
      # 此字段为可选
      type: FileOrCreate

  - name: data
    hostPath:
      # 宿主上目录位置
      path: /data/podman/caddy
      # 此字段为可选
      type: DirectoryOrCreate
