version: "3.9"

x-base: &default-config
  restart: unless-stopped
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000
  stop_grace_period: 1m
  logging:
    driver: json-file
    options:
      max-size: '100m'
      max-file: '1'
  mem_swappiness: 0

services:
  Aria2-Pro:
    container_name: aria2-server
    image: p3terx/aria2-pro
    << : *default-config
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - RPC_SECRET=foo
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Shanghai
    volumes:
      # - ${PWD}/aria2-config:/config
      - ~/Downloads/aria2:/downloads
    # If you use host network mode, then no port mapping is required.
    # This is the easiest way to use IPv6 networks.
    # network_mode: host
    # network_mode: bridge
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp

  # AriaNg is just a static web page, usually you only need to deploy on a single host.
  AriaNg:
    container_name: ariang
    image: p3terx/ariang:test
    command: --port 6880 --ipv6
    << : *default-config
    # network_mode: host
    # network_mode: bridge
    ports:
      - 6880:6880


networks:
  default:
    external:
      name: app


