version: '3.9'

x-base: &default-config
  restart: unless-stopped
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000
  stop_grace_period: 1m
  logging:
    driver: json-file
    options:
      max-size: '100m'
      max-file: '1'
  mem_swappiness: 0
  env_file:
      - .env

services:
  # trino server
  trino:
    image: trinodb/trino:424
    user: root
    hostname: trino
    << : *default-config
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/config/trino/catalog:/etc/trino/catalog
      - trino-data:/lakehouse/data

volumes:
  trino-data: