version: "3.9"

x-base: &default-config
  restart: unless-stopped
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000
  stop_grace_period: 1m
  logging:
    driver: json-file
    options:
      max-size: '100m'
      max-file: '1'
  mem_swappiness: 0

services:
  services:
    image: redis:6
    container_name: redis6
    << : *default-config
    ports:
      - 6379:6379
    volumes:
      - /data/docker/redis/6:/redis
    restart: always

networks:
  default:
    external: true
    name: db
