version: "3.9"

x-base: &default-config
  restart: unless-stopped
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000
  stop_grace_period: 1m
  logging:
    driver: json-file
    options:
      max-size: '100m'
      max-file: '1'
  mem_swappiness: 0

services:
  apm:
    image: docker.elastic.co/apm/apm-server:7.14.2
    container_name: apm7
    hostname: apm7
    << : *default-config
    # volumes:
    #   - ./apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro
    environment:
      output.elasticsearch.hosts: es7:9200
    # Default command: -e -d
    # -d show log to stderr
    # use -E pass overwrite configuration.
    command: -e -E output.elasticsearch.hosts=["es7:9200"] -E apm-server.kibana.enabled=true -E apm-server.kibana.host=http://kibana7:5601 -E apm-server.rum.enable=true
    ports:
      - 8200:8200
    networks:
      - app
      - db

# es7 and kibana7 in db network.
networks:
  db:
    external: true
    name: db
  app:
    external: true
    name: app
