version: "3.9"

x-base: &default-config
  restart: unless-stopped
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000
  stop_grace_period: 1m
  logging:
    driver: json-file
    options:
      max-size: '100m'
      max-file: '1'
  mem_swappiness: 0

services:
  jenkins:
    user: root
    container_name: jenkins
    image: jenkinsci/blueocean
    << : *default-config
    ports:
      - 8085:8080
    volumes:
      - "/data/docker/jenkins:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  default:
    external: true
    name: other
