version: "3.9"

x-base: &default-config
  restart: unless-stopped
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000
  stop_grace_period: 1m
  logging:
    driver: json-file
    options:
      max-size: '100m'
      max-file: '1'
  mem_swappiness: 0

services:
  alist:
    << : *default-config
    container_name: alist
    hostname: alist
    volumes:
    - '/data/docker/alist:/opt/alist/data'
    ports:
    - '5244:5244'
    environment:
    - PUID=0
    - PGID=0
    - UMASK=022

    image: 'xhofe/alist:latest'

networks:
  default:
    external:
      name: app
