version: "3.9"

x-base: &default-config
  restart: unless-stopped
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000
  stop_grace_period: 1m
  logging:
    driver: json-file
    options:
      max-size: '100m'
      max-file: '1'
  mem_swappiness: 0

services:
  server:
    image: mysql:8
    env_file: ./.env
    << : *default-config
    security_opt:
      - seccomp=unconfined
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - db
    volumes:
      - /data/docker/mysql/data:/var/lib/mysql:rw
      - /data/docker/mysql/mysql-files:/var/lib/mysql-files:rw
      - ${PWD}/conf:/etc/mysql/conf.d
    restart: always

  adminer:
    image: adminer
    networks:
      - app
    ports:
      - 8008:8080
    restart: always

networks:
  db:
    external: true
    name: db
  app:
    external: true
    name: app
