version: "3.9"

x-base: &default-config
  restart: unless-stopped
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000
  stop_grace_period: 1m
  logging:
    driver: json-file
    options:
      max-size: '100m'
      max-file: '1'
  mem_swappiness: 0

services:
  logstash:
    image: logstash:7.11.2
    container_name: logstash7
    << : *default-config
    volumes:
      - ${PWD}/pipeline:/usr/share/logstash/pipeline
      - ${PWD}/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      - other
      - db
    ports:
      - 9600:9600
      - 9601:9601/tcp
      - 9601:9601/udp
      - 9602:9602

networks:
  other:
    external: true
    name: other
  db:
    external: true
    name: db
