version: "3.9"

x-base: &default-config
  restart: unless-stopped
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000
  stop_grace_period: 1m
  logging:
    driver: json-file
    options:
      max-size: '100m'
      max-file: '1'
  mem_swappiness: 0

services:
  minio:
    image: 'minio/minio'
    container_name: minio
    << : *default-config
    volumes:
      - '/data/docker/minio:/data'
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'



networks:
  default:
    external: true
    name: app
