version: "3.9"

x-base: &default-config
  restart: unless-stopped
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000
  stop_grace_period: 1m
  logging:
    driver: json-file
    options:
      max-size: '100m'
      max-file: '1'
  mem_swappiness: 0

services:

  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight
    <<: *default-config
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db

volumes:
  redisinsight:

networks:
  default:
    external: true
    name: app
