version: "3.9"

x-base: &default-config
  restart: unless-stopped
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000
  stop_grace_period: 1m
  logging:
    driver: json-file
    options:
      max-size: '100m'
      max-file: '1'
  mem_swappiness: 0

services:

  splash:
    image: scrapinghub/splash
    <<: *default-config
    deploy:
      resources:
        limits:
          memory: 2G
    ports:
        - 8050:8050

networks:
  default:
    external: true
    name: other
